project_id = "uvoncgwthdzwamiizorl"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.invite-customer]
    verify_jwt = false
  [functions.list-customers]
    verify_jwt = false
  [functions.reset-password]
    verify_jwt = false
