
-- Add Phase 1 KPI fields to tenants table
ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS total_customers INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS existing_customers INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS new_customers_monthly INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS new_customer_volume NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS existing_customer_volume NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS order_volume_monthly NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS payment_default_rate NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS commission_rate_actual NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS commission_rate_target NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS sales_side_costs NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS sales_gross_salary NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS fulfillment_gross_salary NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS fulfillment_tool_costs NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cost_per_customer_fulfillment NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ltv_avg_customer NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cac_actual NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cac_target NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS aov_new_customer NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS aov_existing_customer NUMERIC DEFAULT NULL;
